apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: backend-go-pem-secrets
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: SecretStore
  target:
    name: backend-go-pem-secrets  # Nama K8s Secret terpisah untuk file mount
    creationPolicy: Owner
  data:
    - secretKey: banking_private_key.pem  # ini akan menjadi nama file di volume mount
      remoteRef:
        key: secret/backend-go/dev  # Kita override path ini per environment di kustomization.yaml
        property: APP_BANKING_PRIVATE_KEY
